# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [4]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [7]:
print("Numpy Version:",np.__version__)

Numpy Version: 1.19.5


#### Q3 : Créer un vecteur nul de taille 10

In [10]:
v1 = np.empty(10)

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [14]:
v2 = np.empty(10)
v2[5] = 1
print (v2[5])

1.0


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [20]:
v3 = np.arange(10, 50)
print (v3[20])

30


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [23]:
v3 = v3[::-1]
print(v3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [26]:
m1 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(m1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q8 : Créer une matrice identié 3x3 

In [27]:
m2 = np.eye(3)
print(m2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [29]:
m3 = np.random.rand(3,3,3)
print(m3)

[[[0.40481957 0.52146739 0.74799843]
  [0.7146348  0.72057741 0.127104  ]
  [0.10473431 0.56971317 0.28811335]]

 [[0.42373943 0.06946309 0.58167362]
  [0.66737683 0.93535156 0.22536265]
  [0.69894003 0.56573267 0.5797152 ]]

 [[0.66373246 0.51771385 0.35168525]
  [0.15269026 0.72763604 0.46615806]
  [0.16006499 0.57754495 0.84006574]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [35]:
m4 = np.random.rand(10,10)
print("Minimum: {}".format(np.amin(m4)))
print("Maximum: {}".format(np.amax(m4)))

Minimum: 0.008715588563434684
Maximum: 0.9819906749431669


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [43]:
m5 = np.diag(np.array([1,2,3,4]),-1)
print(m5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [47]:
l1 = np.random.rand(5)
print("Total de {} = {}".format(l1, l1.sum()))

Total de [0.32793897 0.72141377 0.51586145 0.01728281 0.74802449] : 2.3305214936667675


#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [48]:
l2 = np.random.rand(5)
print("Moyenne de {} = {}".format(l2, l2.mean()))

Moyenne de [0.57733985 0.71084811 0.03334267 0.40398462 0.19987977] = 0.38507900574732534


#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [50]:
l = [x for x in range(11)]
print(len(l))

11


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [52]:
a1 = np.arange(0, 1, 0.1)
print(a1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [60]:
A = np.array([0,1,2,3,4])
B = np.array([0,1,2,3,6])

if np.greater_equal(A, B).all():
    print("TRUE")
else :
    print("FALSE")

FALSE


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [63]:
a2_float = np.arange(0.0, 10.0, 1.5)
print("Tableau de float : {}".format(a2_float))

a2_int = a2_float.astype(int)
print("Tableau de int : {}".format(a2_int))

Tableau de float : [0.  1.5 3.  4.5 6.  7.5 9. ]
Tableau de int : [0 1 3 4 6 7 9]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)