In [2]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

In [30]:
rdm_mat = np.random.rand(2,2)
print(rdm_mat)

[[0.01783361 0.93733579]
 [0.50824076 0.73445777]]


Donner le type de la variable rdm_mat

In [31]:
print(rdm_mat.dtype)

float64


Donner la somme des éléments de ce tableau 2D

In [32]:
print(rdm_mat.sum())

2.197867927403992


Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [33]:
print(np.amax(rdm_mat, axis=1))

[0.93733579 0.73445777]


Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [34]:
print(np.amax(rdm_mat, axis=0))

[0.50824076 0.93733579]


Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

In [41]:
print(rdm_mat)
rdm_mat_max = np.array([])

for cell in rdm_mat:
    rdm_mat_max = np.append(rdm_mat_max, np.max(cell))
    
print(rdm_mat_max)

[[0.01783361 0.93733579]
 [0.50824076 0.73445777]]
[0.93733579 0.73445777]


On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [42]:
rdm_vect = np.random.randn(100)
rdm_vect.shape

(100,)

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [44]:
print(rdm_vect)
print(np.argmax(rdm_vect))

[ 0.25311945  0.12490025 -0.76573653  1.63032612  0.73953279 -0.3779263
 -0.71083137 -1.7911933  -0.31757889 -0.72867053  0.22551603  0.11095739
 -2.6267494   0.16481054  0.08772707  1.11642325 -0.10460293 -0.50074346
 -0.87207369 -1.19241197  0.84053531 -1.58812692 -0.45735823 -1.37773681
 -0.6081273  -0.12175233 -0.21394957  0.03315243  0.68406257  1.53539985
 -0.09271063  2.18187189 -1.59623803 -0.22980654  0.14944945  1.04077574
 -1.21793823  0.99576645  1.74869853  0.73312953  1.59009072  0.50599184
 -0.84762821 -1.43120507 -0.30939458  1.20800307  0.6570186   0.32871398
 -0.53735115  1.35989638  1.38768714 -0.1061481  -0.46241773  0.48877374
  1.4264689  -0.57437466  1.08369188  0.86495671  1.83159272 -0.03456877
  0.8467671   1.92410868  0.43886621  0.06074062  0.66990689  1.12287473
  0.24649477  0.04434885 -0.25319856 -1.06927876  1.23117047 -0.47820697
  0.99625125  0.09541675 -2.14607874  0.89503644 -0.61409998  0.37614335
  1.15719127  0.26475487 -0.78960509 -1.28511591  0.

Afficher cette valeur 

Convertir le vecteur en un tableau 10, 10

array([[-2.99441404e-01,  1.78419461e+00,  1.62824730e+00,
         5.76998680e-01, -1.00798820e+00, -1.17629307e-01,
        -9.59793928e-01,  2.51709966e+00, -4.57689923e-01,
         5.64083233e-01],
       [ 1.08857553e+00,  1.25553582e+00,  1.41174036e+00,
         7.04405054e-01,  1.76417213e+00,  2.95989674e-01,
        -2.48375632e-01, -2.73836034e-01, -1.54983085e+00,
         6.81613252e-01],
       [-2.30990058e-04, -4.59307174e-01, -2.76918402e-01,
         1.39001379e-01, -3.43068545e-01,  1.38215348e+00,
         2.21448409e-01,  1.34330582e+00, -3.28983492e-01,
        -1.48319122e+00],
       [ 6.03851209e-02,  4.42199292e-01, -1.96886665e+00,
        -3.67291142e-01, -5.92191022e-01, -1.07593701e+00,
        -9.94270773e-01,  1.75063721e+00,  1.02451250e+00,
        -5.22313882e-03],
       [ 1.35937353e+00,  1.37572412e+00, -1.26344802e+00,
        -2.74771048e-01,  2.38997913e-01, -7.38658517e-01,
         1.31298051e+00,  1.60500160e-01,  1.03054547e-01,
         1.

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

array([-2.45928276e-01,  3.30057119e-01, -6.94069374e-02,  1.16367130e-02,
       -7.35080583e-02,  1.78359994e-04, -1.12472416e-01,  9.99337195e-01,
       -1.69671892e-01,  1.56672647e-01])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

array([ 4.22808072,  5.1299893 ,  0.19420926, -1.72604562,  3.31269044,
       -7.18438496,  1.73127593, -1.61666039,  1.17147191,  3.02831796])

Calculer la somme pour chaque ligne (sans boucles)

array([-2.45928276e+00,  3.30057119e+00, -6.94069374e-01,  1.16367130e-01,
       -7.35080583e-01,  1.78359994e-03, -1.12472416e+00,  9.99337195e+00,
       -1.69671892e+00,  1.56672647e+00])